"""
The FOCAL mnemonic reference (docs/mnemonic_dialects_plan.md sec 3.8):
every instruction's display and canonical names, the other spellings
text import accepts, the character-substitution table and the trigraph
table, all generated from memory/mnemonics.py and memory/trigraphs.py so
they can't drift from what the code actually accepts.

Two consumers:

- The Help > FOCAL Mnemonics Reference dialog, which calls
  mnemonic_reference_rows() (and the two small table functions) at run
  time.
- docs/mnemonics.md, written by `python -m memory.mnemonic_doc` (run
  from src/). tests/test_mnemonic_doc.py fails if the committed file is
  out of date.
"""

import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

from .mnemonic_dialects import DIALECTS
from .mnemonics import Entry, OpKind, character_substitutions, entries
from .trigraphs import shorthand_trigraphs, unicode_to_trigraphs

logger = logging.getLogger(__name__)

DEFAULT_OUTPUT = Path(__file__).resolve().parents[2] / "docs" / "mnemonics.md"


@dataclass(frozen=True)
class ReferenceRow:
    """One instruction in the reference.

    `other_spellings` lists every other plain-ASCII spelling import
    accepts -- character-substitution variants (SIGMAREG, X!=Y?) and
    dialect spellings (P->R, GOTO) -- followed by the trigraph form
    (\\EREG) for a display name with FOCAL symbols in it. Upper/lower
    case variants and the ∑-for-Σ fold aren't listed. `search_text`
    holds all of those, uppercased, for filtering."""

    display: str
    canonical: str
    other_spellings: Tuple[str, ...]
    encoding: str
    notes: str
    search_text: str


def _encoding(entry: Entry) -> str:
    kind, code = entry.op.kind, entry.op.code
    if kind is OpKind.FUNCTION:
        return f"0x{code:02X}"
    if kind is OpKind.XROM:
        byte1, byte2 = code
        mm = ((byte1 & 0x07) << 2) | (byte2 >> 6)
        return f"XROM {mm:02d},{byte2 & 0x3F:02d}"
    return ""


def _notes(entry: Entry) -> str:
    if not entry.programmable:
        return "keyboard only"
    if entry.op.kind is OpKind.KEYWORD:
        return "text keyword"
    if entry.dm41x_only:
        return "DM41X only"
    return ""


def _row(entry: Entry) -> ReferenceRow:
    # Registry order: substitution variants first, then dialect spellings.
    others = [
        spelling
        for spelling, _source in entry.aliases
        if spelling.isascii() and spelling not in (entry.display, entry.canonical)
    ]
    trigraph_form = unicode_to_trigraphs(entry.display)
    if trigraph_form != entry.display:
        others.append(trigraph_form)
    others = tuple(others)
    everything = {entry.display, entry.canonical, *others} | {
        s for s, _ in entry.aliases
    }
    return ReferenceRow(
        display=entry.display,
        canonical=entry.canonical,
        other_spellings=others,
        encoding=_encoding(entry),
        notes=_notes(entry),
        search_text=" ".join(sorted(s.upper() for s in everything)),
    )


def mnemonic_reference_rows() -> List[ReferenceRow]:
    """Every registered instruction, sorted by canonical name (so ΣREG
    sorts as SREG, next to SQRT, rather than after Z), ignoring case."""
    rows = [_row(e) for e in entries()]
    return sorted(rows, key=lambda r: (r.canonical.upper(), r.canonical))


_POWERS_ONLY = "(powers only: X↑2, Y↑X, E↑X, 10↑X, E↑X-1)"


def substitution_rows() -> List[Tuple[str, str, str]]:
    """(glyph, hp41uc's canonical stand-in, the other accepted stand-ins).
    A stand-in accepted only in the power functions is marked as such."""
    rows = []
    for glyph, standins, power_only in character_substitutions():
        others = list(standins[1:])
        others += [f"{s} {_POWERS_ONLY}" for s in power_only]
        rows.append((glyph, standins[0], ", ".join(others)))
    return rows


def trigraph_rows() -> List[Tuple[str, str, str]]:
    """(escape text, the character it produces, its FOCAL byte as hex)."""
    return [
        (escape, symbol, f"0x{byte:02X}")
        for escape, byte, symbol in shorthand_trigraphs()
    ]


def _code(text: str) -> str:
    """`text` as a Markdown table-cell code span: backticks, with the
    table-cell pipe escaped (GitHub renders `\\|` inside a code span in
    a table as a literal |)."""
    if not text:
        return ""
    return "`" + text.replace("|", "\\|") + "`"


def render_mnemonic_reference() -> str:
    """The whole reference as Markdown (docs/mnemonics.md)."""
    out = [
        "# FOCAL Mnemonics Reference",
        "",
        "<!-- GENERATED by `python -m memory.mnemonic_doc` (run from src/)"
        " from memory/mnemonics.py. Do not edit by hand. -->",
        "",
        "DM41_Explorer reads HP-41 program listings (`.txt`) written in",
        "several spellings. Each instruction has:",
        "",
        "- a **display** name: what the HP-41/DM41L shows, and what the app",
        "  shows (e.g. `ΣREG`, `X≠Y?`, `ENTER↑`);",
        "- a **canonical** name: the plain-ASCII spelling hp41uc uses, which",
        "  the app writes when exporting a listing (e.g. `SREG`, `X#Y?`,",
        "  `ENTER`);",
        "- **other spellings**: every other form import accepts, including",
        "  the character substitutions (`SIGMAREG`, `X!=Y?`), hp41uc's",
        "  alternate words (`P->R`, `GOTO`) and the trigraph form (`\\EREG`).",
        "",
        "Import accepts any of these in upper or lower case, and `∑`",
        "(Option-W on a Mac) in place of `Σ`.",
        "",
        "The Key Assignment dialog accepts the same spellings.",
        "",
        "A note of *DM41X only* marks a function that the DM41X (and DM41XN)",
        "added to the HP-41CX set. A DM41L doesn't have it, but programs and",
        "key assignments that use it still open, display and save.",
        "",
        "## Instructions",
        "",
        "| Display | Canonical (export) | Other spellings | Encoding | Notes |",
        "|---|---|---|---|---|",
    ]
    for row in mnemonic_reference_rows():
        others = ", ".join(_code(s) for s in row.other_spellings)
        out.append(
            f"| {_code(row.display)} | {_code(row.canonical)} | {others} "
            f"| {row.encoding} | {row.notes} |"
        )
    out += [
        "",
        "## Character substitutions",
        "",
        "Each special character in a display name can be typed as any of",
        "these ASCII stand-ins.",
        "",
        "| Character | Canonical stand-in | Also accepted |",
        "|---|---|---|",
    ]
    for glyph, standins, power_only in character_substitutions():
        also = [_code(s) for s in standins[1:]]
        also += [f"{_code(s)} {_POWERS_ONLY}" for s in power_only]
        out.append(f"| {glyph} | {_code(standins[0])} | {', '.join(also)} |")
    out += [
        "",
        "## Trigraphs",
        "",
        "A backslash escape stands for one FOCAL character, in instruction",
        "names and in quoted ALPHA text. Escapes are case-sensitive (`\\E` is",
        "Σ; `\\e` is an error). Any byte can also be written as a backslash",
        "and exactly three decimal digits (`\\126` is Σ). See",
        "[trigraphs.md](trigraphs.md).",
        "",
        "| Escape | Character | FOCAL byte |",
        "|---|---|---|",
    ]
    for escape, symbol, byte in trigraph_rows():
        out.append(f"| {_code(escape)} | {_code(symbol)} | {byte} |")
    out += ["", "## Sources", ""]
    for dialect in DIALECTS:
        out.append(f"- **{dialect.name}**: {dialect.source}")
    out.append("")
    return "\n".join(out)


def main(argv: List[str]) -> int:
    """`python -m memory.mnemonic_doc [output.md]` -- writes the reference
    (default: docs/mnemonics.md)."""
    output = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    output.write_text(render_mnemonic_reference(), encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
